[Build]
BuildSources=
    %D
    %D/droid-juicer:droid-juicer
WithNetwork=yes

[Content]
BuildPackages=
    cargo
    clang-devel
    gcc
    git-core
    pkgconf-pkg-config
ExtraTrees=../droid-juicer/mkosi.extra
