[package]
summary = "Extract firmware from Android vendor partitions"
description = """\
droid-juicer extracts binary firmware from Android vendor partitions and
installs it into /lib/firmware, avoiding redistributing vendor blobs.
"""
extra-files = [
    "%dir %{_sysconfdir}/droid-juicer",
    "%{_unitdir}/droid-juicer.service",
    "%dir %{_datadir}/droid-juicer",
    "%dir %{_datadir}/droid-juicer/configs",
    "%{_datadir}/droid-juicer/configs/*.toml",
]
bin-package-extra = """\
Requires(post): systemd
Requires(preun): systemd
Requires(postun): systemd

%post
%systemd_post droid-juicer.service

%preun
%systemd_preun droid-juicer.service

%postun
%systemd_postun_with_restart droid-juicer.service
"""

[scripts]
install.post = [
    "install -Dpm 0644 droid-juicer.service %{buildroot}%{_unitdir}/droid-juicer.service",
    "mkdir -p %{buildroot}%{_sysconfdir}/droid-juicer %{buildroot}%{_datadir}/droid-juicer/configs/",
    "install -Dpm 0644 configs/*.toml %{buildroot}%{_datadir}/droid-juicer/configs/",
]

[requires]
build = ["systemd-rpm-macros"]
