[Service]
ExecStartPost=modprobe -a qcom_q6v5 qcom_q6v5_pas qcom_q6v5_adsp qcom_q6v5_mss qcom_q6v5_wcss qcom_wcnss_pil
ExecStartPost=modprobe -a qcom_common qcom_sysmon qcom_pil_info
ExecStartPost=modprobe -a ath10k_snoc wcn36xx wcnss_ctrl
ExecStartPost=modprobe -a btqca btqcomsmd hci_uart
