apiVersion: v1
kind: ConfigMap
metadata:
  name: rokkitpokkit-caddy
  namespace: rokkitpokkit
data:
  Caddyfile: |-
    {
      admin off
      auto_https off
    }

    :80 {
      respond /healthz "ok" 200

      @artifact_paths path /casync/* /channels/* /images/*
      handle @artifact_paths {
        redir https://cdn.rokkitpokkit.samcday.com{uri} 302
      }

      @rawhide path /rawhide
      handle @rawhide {
        redir https://cdn.rokkitpokkit.samcday.com/channels/rawhide 302
      }

      respond "🚀📱" 200
    }
