apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: rokkitpokkit-infra-tofu
  namespace: rokkitpokkit
spec:
  interval: 10m
  approvePlan: auto
  path: ./infra/tofu
  sourceRef:
    kind: GitRepository
    name: rokkitpokkit
    namespace: flux-system
  varsFrom:
    - name: tofu-vars
      kind: Secret
  runnerPodTemplate:
    spec:
      envFrom:
        - name: tofu-env
          kind: Secret
  writeOutputsToSecret:
    name: tofu-outputs
