apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tofu
  namespace: rokkitpokkit
spec:
  interval: 10m
  approvePlan: auto
  path: ./infra/tofu
  sourceRef:
    kind: GitRepository
    name: rokkitpokkit
  varsFrom:
    - name: tofu-bucket-vars
      kind: Secret
    - name: tofu-vars
      kind: Secret
  runnerPodTemplate:
    spec:
      envFrom:
        - secretRef:
            name: tofu-env
  writeOutputsToSecret:
    name: tofu-outputs
