apiVersion: v1
kind: Secret
metadata:
    name: tofu-env
    namespace: rokkitpokkit
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:RIOpd48SqMIof/PH1C+ksKj1LxNgw2q7zAun66VhsOjZcZ1xYM+Q4hjtJ9NexZ9oG33IpKPtY6zTAvWQFHcVp9l3Owu9RYw1WeZkQHvmC/cP31S8SQQ0/7VpHosk,iv:Nex9+GldK0jrNdewnZJuBvvxNpp479EJc7Mz+FxqYog=,tag:HTnOPKWD1bjKBAisnit0UQ==,type:str]
sops:
    age:
        - recipient: age1utf3jfmexu3zsfqphejlh8ptx7av09jdh9n305jaqwa5s0nqevxsja4r76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYkpNaUtpbk1LSFF3ZmMz
            MGY2MFgybzJYcFFkTDJtZUYraFhyODFjcVVFCm5XTWQ2cjVkVTRFR3d6OHpBV2Jq
            OFZFRVNBKzJWeTVJT1Zudm1sbFMrQkUKLS0tIDhJZWxoWHBDLzVTM3MxTkZGaENq
            TTB5dDAvUWdsNnp4MkN4amZiNXQrWjAKIJnDgFdXh84G+jQfRmnm/i6nig2xsVtC
            H0Exu9Oq5MrFRGBQzAWLvCZPPBwIHgFHuBuR0MQZ7uVSOGC54lFuCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T03:57:40Z"
    mac: ENC[AES256_GCM,data:dpr138hLt4OEh9NzpCU5yO1Z2LpqEz1/NDperIFVmt8Ww4dHVHlqDZ6aJOCmJjhZtYgQ5nLTnY/Do56hhOxka5UmdlfiRYBWofPdyUDWzrQu0I6FCI48754KWGGFzN7c9nBI3jv8cTEoSVnxMp2aIOX+h8Pi0/6C9mXcsEnj8Sw=,iv:dAw+255ThXD64JajbndPaYZLM66gaB2Qc6NilOqhxyE=,tag:xrPqFL1DL0aBm0AGVtAVRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
