apiVersion: ENC[AES256_GCM,data:FRo=,iv:u8/EY9QgHT500tWoVqMtWveHsaJZr4RZ2da4E2QniCk=,tag:24ldLf4BIDWJDHXuuejLWw==,type:str]
kind: ENC[AES256_GCM,data:oWiXI985,iv:0hz+x5IUkWPIpobHVxCxyU46U6oj/m+TmbS3dGyzgd8=,tag:g0wMwEuQNEh/ui636ogtCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4Vcav9tMqEI=,iv:DMkib8lSWuYbLiZqaqb+c/YirjZce/rEG8UEzhZGxZ4=,tag:lMxAyvJ+5wnUtmH1UzD79Q==,type:str]
    namespace: ENC[AES256_GCM,data:DSIBj+CRP7U9dT0w,iv:ntXhWm3Lc/XsokFzxEzzzTUJ2WCo4pQc4Jq1669//Y0=,tag:Z8SR1DJB2Dls+tScxSmaRQ==,type:str]
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:mThcZWOHQopN5H7F+vgE6V1VHtLJhaLdyjcfT5ZQEYARqJtXjz/vcAl4Mpm87j9tEOdP1KQF5sJlC5EPp5tCOMNyKhEHHO6LFKFITTdutYtsJ6mGfJsIF5JDGxbs,iv:F0w6Ql/WpTabQYw32TXyAuxpDTCaXPwB3CcXA9FC0LU=,tag:RqL4jl0CORGmSqHoNK/a4g==,type:str]
sops:
    age:
        - recipient: age1utf3jfmexu3zsfqphejlh8ptx7av09jdh9n305jaqwa5s0nqevxsja4r76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UUhidVd3UnR3K3l4Ym5T
            WU00RFREQ2lqRkg0SDRTOTY0RVUyZmlxK1c4CmtGamRWeXEzcDk4aXErV0lNQW93
            WDZlb1FXQTlnSDBkSjVkSkw1eHk5R3cKLS0tIGRDdDFEZXlOT0xFTm5NVVlKZ3Ba
            TTVmWE9kMHExMUtwbmREekgrS013T2sK4Y/vJndQ1Liq+qsahjPSmj+9T6FlkgHI
            RP/8vcjq3Ce7C6VGGP3FFf5yQgKaFN27XnO/D21oWJLqAz7vt6RdYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T01:23:17Z"
    mac: ENC[AES256_GCM,data:7mi+ehOs4oDdAjAXovG1MqYt+kAAK/d3gyYDTRIc4/N0MNY/Powis1sK6pQIKMmXJFC+Flo/C600j7dWePvlLfrxmPxHu4YVLnQATEosbJBYHQTqBFvvItxG/ez5GHe/JcnYJUZOgIRrzqb9fZ3Cjx04crYEcORp4H3uJuvn4p4=,iv:5VsVIYzFV5lFxeguXTu1wuUhTSK/It7TIYwGhmJ9WGE=,tag:98ck8fRgPf5q45a028YrGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
