apiVersion: v1
kind: Secret
metadata:
    name: tofu-env
    namespace: rokkitpokkit
type: Opaque
stringData: {}
sops:
    age:
        - recipient: age1utf3jfmexu3zsfqphejlh8ptx7av09jdh9n305jaqwa5s0nqevxsja4r76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcTlYbmRUK3Zhb2FmYUdM
            Z1RDaTAySHArcFFub1ljblhzNjdyUkhkMWdBCmxoNXp0NmNhZlhrY3FNVFYyZnhq
            K0t2QmcyeEo3dzF0TUJOcjFqNXBtV28KLS0tIHY3WE5UN2d1aFJIYzg2Wkg2WXpJ
            TCtRSmg1cHVFVkZkeG0xTkMvbU1PZncKfGlMgp6Vt/iy8KyaCTLYGs8MvdqmD3CS
            vNZdLtSs1gDgXVO+JetoIvCU5SNevigg1WiDa/Ndd/w8MvXOMXRgkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T04:01:00Z"
    mac: ENC[AES256_GCM,data:LA5pWmvQhn92FpCbYtmsRV+Sm3TUI+Z+XKhsmUqAb5TK7tLgsYYSRk4PxrjDsizwFa+OWGuan1E5zC636Cc68NgXZLsV4hNjNsqEnSZLx6F2N9MR1dWRa7uJp6aekwTeu/vRa69umGv7r4AOsjdrdgdk9OHhMVeRIBS5Fhd5Zqk=,iv:N6FzgiFtCKPqViHIZuiz9KTVwUOEqC+r18k7U8O1yoc=,tag:aJkiOw/LjMjJs6K2F+uOqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
