apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rokkitpokkit-public-tls
spec:
  secretName: rokkitpokkit-public-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - rokkitpokkit.samcday.com
    - xn--nu8h3y.samcday.com
